Repository googleapis/java-iam, pull requests merged in 2020-09, with the labels that each got.

#34 build: fix synth.py to generate only proto/grpc targets without gapic assembly tarball
  synth.py
Labels: cla: yes

#38 chore: regenerate common templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  .kokoro/release/stage.cfg
  proto-google-iam-v1/src/main/java/com/google/iam/v1/AuditConfigDelta.java
  proto-google-iam-v1/src/main/java/com/google/iam/v1/Binding.java
  proto-google-iam-v1/src/main/java/com/google/iam/v1/BindingDelta.java
  proto-google-iam-v1/src/main/java/com/google/iam/v1/GetIamPolicyRequest.java
  proto-google-iam-v1/src/main/java/com/google/iam/v1/GetPolicyOptions.java
  proto-google-iam-v1/src/main/java/com/google/iam/v1/Policy.java
  proto-google-iam-v1/src/main/java/com/google/iam/v1/PolicyDelta.java
  proto-google-iam-v1/src/main/java/com/google/iam/v1/SetIamPolicyRequest.java
  proto-google-iam-v1/src/main/java/com/google/iam/v1/TestIamPermissionsRequest.java
  proto-google-iam-v1/src/main/java/com/google/iam/v1/logging/AuditData.java
  synth.metadata
  synth.py
Labels: automerge, cla: yes, context: partial

#40 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: iam, automerge, cla: yes

#41 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: iam, automerge, cla: yes, context: full

#42 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
