Repository googleapis/java-iam, pull requests merged in 2021-08, with the labels that each got.

#163 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, api: iam, context: full

#170 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: iam

#171 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: iam, context: full
