Repository googleapis/java-iam, pull requests merged in 2021-09, with the labels that each got.

#187 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: automerge, kokoro:force-run, cla: yes, api: iam

#188 chore: re-generated to pick up changes from self
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  synth.metadata
Labels: cla: yes, api: iam, context: none

#177 ci: removing linkage-monitor from the required checks
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  renovate.json
  synth.metadata
Labels: cla: yes, api: iam, context: partial, context: full

#195 chore: removes linkage monitor from required
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: iam

#201 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: iam

#202 chore(java): remove dependencyDashboardLabel config from renovate.json
  renovate.json
  synth.metadata
Labels: cla: yes, api: iam, context: full

#204 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: iam

#206 chore: change branch master to main in github configurations
  .github/blunderbuss.yml
  .github/workflows/ci.yaml
  README.md
Labels: automerge, cla: yes, api: iam
